name: sealed_generator
description: Codegeneration library for making 'when' statement for Dart.
version: 1.0.1
author: Zabelnykov Serhii <ReginFell@gmail.com>
homepage: https://github.com/ReginFell/Dart-sealed-codegen

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^2.0.0
  meta: ^1.3.0
  source_gen: ^1.0.0
  recase: ^3.0.1
  analyzer: ^1.3.0

dev_dependencies:
  build_test: ^2.0.0
  build_runner: ^1.12.2
  test: ^1.16.8
